<script>
  import { onMount } from 'svelte';

  let open = $state(false);
  let query = $state('');
  let results = $state([]);
  let loading = $state(false);
  let pagefind = $state(null);
  let unavailable = $state(false);
  let inputEl = $state();

  // BASE_URL is replaced by Vite at build time → '/events-all-the-way-down/'
  const base = import.meta.env.BASE_URL;

  onMount(() => {
    function onKey(e) {
      if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
        e.preventDefault();
        open = !open;
      }
      if (e.key === 'Escape' && open) {
        open = false;
      }
    }
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  });

  $effect(() => {
    if (open) {
      // Focus input after DOM updates
      setTimeout(() => inputEl?.focus(), 50);
      // Lazy-load pagefind index on first open
      if (!pagefind && !unavailable) loadPagefind();
    } else {
      query = '';
      results = [];
    }
  });

  async function loadPagefind() {
    try {
      // pagefind.js is generated by `npm run build` at {base}pagefind/pagefind.js
      const pf = await import(/* @vite-ignore */ `${base}pagefind/pagefind.js`);
      await pf.init();
      pagefind = pf;
    } catch {
      unavailable = true;
    }
  }

  async function onInput(e) {
    query = e.target.value;
    if (!query.trim() || !pagefind) { results = []; return; }
    loading = true;
    const res = await pagefind.search(query);
    const data = await Promise.all(res.results.slice(0, 8).map(r => r.data()));
    results = data;
    loading = false;
  }

  function closeOnBackdrop(e) {
    if (e.target === e.currentTarget) open = false;
  }
</script>

<!-- Search trigger button (renders inside nav via slot in Layout) -->
<button class="search-trigger" onclick={() => open = true} aria-label="Search (Ctrl+K)">
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
    <circle cx="11" cy="11" r="8"/><path d="m21 21-4.35-4.35"/>
  </svg>
  <span class="search-hint">Search</span>
  <kbd>⌘K</kbd>
</button>

<!-- Modal overlay -->
{#if open}
<!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
<div class="overlay" onclick={closeOnBackdrop} role="dialog" aria-modal="true" aria-label="Search">
  <div class="modal">
    <div class="search-bar">
      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
        <circle cx="11" cy="11" r="8"/><path d="m21 21-4.35-4.35"/>
      </svg>
      <input
        bind:this={inputEl}
        type="search"
        placeholder="Search posts…"
        value={query}
        oninput={onInput}
        autocomplete="off"
        spellcheck="false"
      />
      <button class="close-btn" onclick={() => open = false} aria-label="Close search">Esc</button>
    </div>

    <div class="results">
      {#if unavailable}
        <p class="hint">Search unavailable in dev mode — run <code>npm run build</code> first.</p>
      {:else if loading}
        <p class="hint">Searching…</p>
      {:else if query && results.length === 0}
        <p class="hint">No results for "<strong>{query}</strong>".</p>
      {:else if results.length > 0}
        <ul>
          {#each results as r}
          <li>
            <a href={r.url} onclick={() => open = false}>
              <span class="result-title">{r.meta?.title ?? 'Untitled'}</span>
              {#if r.excerpt}
              <span class="result-excerpt">{@html r.excerpt}</span>
              {/if}
            </a>
          </li>
          {/each}
        </ul>
      {:else if !query}
        <p class="hint">Type to search all posts and the manifesto.</p>
      {/if}
    </div>
  </div>
</div>
{/if}

<style>
  /* Trigger button */
  .search-trigger {
    display: flex;
    align-items: center;
    gap: 0.4rem;
    background: none;
    border: 1px solid var(--color-border);
    border-radius: 4px;
    padding: 0.2rem 0.6rem;
    font-size: 0.8rem;
    color: var(--color-muted);
    cursor: pointer;
    transition: border-color 0.1s, color 0.1s;
    white-space: nowrap;
  }

  .search-trigger:hover {
    border-color: var(--color-accent);
    color: var(--color-accent);
  }

  .search-hint { display: none; }
  @media (min-width: 640px) { .search-hint { display: inline; } }

  kbd {
    font-family: ui-monospace, monospace;
    font-size: 0.7rem;
    opacity: 0.6;
    display: none;
  }
  @media (min-width: 768px) { kbd { display: inline; } }

  /* Overlay */
  .overlay {
    position: fixed;
    inset: 0;
    background: rgba(0, 0, 0, 0.45);
    z-index: 500;
    display: flex;
    align-items: flex-start;
    justify-content: center;
    padding-top: 10vh;
  }

  .modal {
    background: var(--color-bg);
    border: 1px solid var(--color-border);
    border-radius: 6px;
    width: min(600px, 92vw);
    max-height: 70vh;
    display: flex;
    flex-direction: column;
    overflow: hidden;
    box-shadow: 0 8px 32px rgba(0,0,0,0.18);
  }

  .search-bar {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    padding: 0.875rem 1rem;
    border-bottom: 1px solid var(--color-border);
    color: var(--color-muted);
  }

  .search-bar input {
    flex: 1;
    background: none;
    border: none;
    outline: none;
    font-family: var(--font-serif);
    font-size: 1rem;
    color: var(--color-text);
  }

  .search-bar input::placeholder { color: var(--color-muted); }

  .close-btn {
    background: none;
    border: 1px solid var(--color-border);
    border-radius: 3px;
    padding: 0.1rem 0.35rem;
    font-size: 0.75rem;
    font-family: ui-monospace, monospace;
    color: var(--color-muted);
    cursor: pointer;
  }

  .results {
    overflow-y: auto;
    padding: 0.5rem 0;
  }

  .hint {
    padding: 1rem 1.25rem;
    color: var(--color-muted);
    font-size: 0.9rem;
    margin: 0;
  }

  ul {
    list-style: none;
    padding: 0;
    margin: 0;
  }

  li a {
    display: block;
    padding: 0.75rem 1.25rem;
    border-bottom: none;
    transition: background 0.1s;
    text-decoration: none;
  }

  li a:hover { background: var(--color-surface); }

  .result-title {
    display: block;
    font-weight: 600;
    color: var(--color-text);
    margin-bottom: 0.2rem;
    font-size: 0.95rem;
  }

  .result-excerpt {
    display: block;
    color: var(--color-muted);
    font-size: 0.85rem;
    line-height: 1.5;
  }

  /* Pagefind highlights */
  :global(mark) {
    background: oklch(from var(--color-accent) l c h / 0.2);
    color: var(--color-text);
    border-radius: 2px;
    padding: 0 1px;
  }
</style>
